
FROM fedora:36

WORKDIR /godot

RUN dnf -y install --setopt=install_weak_deps=False \
    bash bzip2 curl file findutils git make nano patch pkgconfig python3-pip unzip which xz \
    && \
    pip install scons==4.4.0

CMD /bin/bash